version: '3.9'

services:
  backend:
    build: ./service
    container_name: express_backend_flower
    ports:
      - "5001:5001"
    env_file:
      - ./service/.env
    restart: unless-stopped

  frontend:
    build: ./web
    container_name: react_frontend_flower
    ports:
      - "8080:80"
    env_file:
      - ./web/.env
    restart: unless-stopped